-- Allow users to see their own manual import batches even without explicit area membership
ALTER POLICY manual_batches_select
ON public.manual_import_batches
USING (
  hub_is_admin()
  OR hub_user_has_area(area_id)
  OR imported_by = auth.uid()
);

-- Allow users to see CS implantação rows generated by their own batches
ALTER POLICY cs_impl_select
ON public.cs_implantacoes_records
USING (
  hub_is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.manual_import_batches b
    WHERE b.id = cs_implantacoes_records.batch_id
      AND (
        hub_user_has_area(b.area_id)
        OR b.imported_by = auth.uid()
      )
  )
);

-- Keep consistency for CS fila rows linked to own batches
ALTER POLICY cs_fila_select
ON public.cs_fila_manual_records
USING (
  hub_is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.manual_import_batches b
    WHERE b.id = cs_fila_manual_records.batch_id
      AND (
        hub_user_has_area(b.area_id)
        OR b.imported_by = auth.uid()
      )
  )
);

-- Keep consistency for manual rows linked to own batches
ALTER POLICY manual_rows_select
ON public.manual_import_rows
USING (
  hub_is_admin()
  OR EXISTS (
    SELECT 1
    FROM public.manual_import_batches b
    WHERE b.id = manual_import_rows.batch_id
      AND (
        hub_user_has_area(b.area_id)
        OR b.imported_by = auth.uid()
      )
  )
);