-- ============================================================================
-- AVISO DE SEGURANÇA — NÃO EXECUTAR ESTE ARQUIVO
-- ============================================================================
-- Este arquivo foi neutralizado em 2026-04-21 (pentest rodada 2).
-- O conteúdo original criava políticas RLS que concediam acesso anônimo
-- (role: anon) irrestrito à tabela public.tickets — expondo dados LGPD.
--
-- As políticas de teste foram corretamente removidas pelas migrations oficiais:
--   20260130142646  →  dropa "Allow anonymous insert/update for testing"
--   20260204134410  →  dropa "Allow anonymous read for testing"
--
-- Executar o conteúdo original deste arquivo em qualquer ambiente recriaria
-- essas políticas perigosas. Por isso o SQL foi removido deste arquivo.
--
-- Para testar tickets, use uma conta autenticada com a role correta.
-- NUNCA use a role anon para acessar dados de produção.
-- ============================================================================
